name: Deploy to GitHub Pages and Server

on:
  push:
    branches:
      - main  # 每次推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v2  # 检出代码

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.5.0'  # 设置 Node.js 版本

      # 安装依赖
      - name: Install Dependencies
        run: |
          npm install 

      # 构建静态文件
      - name: Build Static Files
        run: |
          npm run build  # 构建 VuePress 静态文件


      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git config --global user.name "kidoneself"
          git config --global user.email "8768611@qq.com"
          cp -r .vuepress/dist/* .
          git add -A
          git commit -m "Deploy built files"
          git push -f https://secrets.GITHUB_TOKEN@github.com/kidoneself/kidoneself.github.io.git gh-pages

      - name: Deploy to Server via SSH
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into server and pull code
        run: |
           ssh -o StrictHostKeyChecking=no root@43.134.58.162 << 'EOF'
             cd /home/kidoneself.github.io
             git pull origin gh-pages
             sudo systemctl restart caddy
           EOF