name: Deploy to GitHub Pages and Server

on:
  push:
    branches:
      - main  # 每次推送到 main 分支时触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v2  # 检出代码

      # 设置 Node.js 环境
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.5.0'  # 设置 Node.js 版本

      # 安装依赖
      - name: Install Dependencies
        run: |
          npm install 

      # 构建静态文件
      - name: Build Static Files
        run: |
          npm run build  # 构建 VuePress 静态文件


      - name: Deploy to GitHub Pages
        run: |
          git checkout --orphan gh-pages
          git config --global user.name "kidoneself"
          git config --global user.email "8768611@qq.com"
          # 确保 dist 文件夹不被删除
          git rm -rf .  
          git reset .vuepress/dist
          cp -r .vuepress/dist/* .
          git add -A
          git commit -m "Deploy built files"
          git push -f https://secrets.GITHUB_TOKEN@github.com/kidoneself/kidoneself.github.io.git gh-pages

      - name: 检出代码
        uses: actions/checkout@v2

      - name: 设置 SSH 密钥
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # 可选：跳过主机密钥验证（对于 CI 很有用）
          touch ~/.ssh/known_hosts
          ssh-keyscan -H 43.134.58.162 >> ~/.ssh/known_hosts

      - name: 通过 SSH 连接服务器并拉取代码
        run: |
          ssh -o StrictHostKeyChecking=no root@43.134.58.162 << 'EOF'
            cd /home/kidoneself.github.io
            git pull origin gh-pages
            sudo docker restart caddy
          EOF